# Generated by Django 5.0.7 on 2024-08-02 19:11

import django.db.models.deletion
import postmanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=55)),
                ('post_image', models.FileField(upload_to=postmanagement.models.user_post_upload_to)),
                ('comments_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.user')),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.user')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postmanagement.posts')),
            ],
            options={
                'verbose_name_plural': 'postlikes',
            },
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('commented_at', models.DateTimeField()),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.user')),
                ('parent_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postmanagement.postcomments')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postmanagement.posts')),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='PostCommentLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.user')),
                ('post_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postmanagement.postcomments')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postmanagement.posts')),
            ],
            options={
                'verbose_name_plural': 'postcommentlikes',
            },
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postmanagement.posts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.user')),
            ],
            options={
                'verbose_name_plural': 'posttags',
            },
        ),
    ]
