# Generated by Django 5.0.7 on 2024-08-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcommentlikes',
            options={'verbose_name_plural': 'post comment likes'},
        ),
        migrations.AlterModelOptions(
            name='postlikes',
            options={'verbose_name_plural': 'post likes'},
        ),
        migrations.AlterModelOptions(
            name='posttags',
            options={'verbose_name_plural': 'post tags'},
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='parent_comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postmanagement.postcomments'),
        ),
    ]
