# Generated by Django 5.0.7 on 2024-08-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmanagement', '0002_alter_postcommentlikes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
