# Generated by Django 5.0.7 on 2024-08-03 19:46

import django.core.validators
import usermanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/profile_photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), usermanagement.models.validate_file_size]),
        ),
    ]
